### ISSUE TITLE
Feature request - sending invitation links

### ISSUE THREAD

**Issue by nteetor** [Azure/AzureAuth#21]
When an external user requests access to an application they often see a message saying they are not a part of the tenant. The azure docs seem confident users must be granted access through an invitation link (i.e. the application can't simply allow them access). So, it would be handy if there were an option for sending invitation links as part of the auth process in this package.

**Comment by Hong-Revo** [comment]
AzureAuth is strictly about authentication; user management is handled by the Graph API.

Also, note that if you're writing an app for a customer, you should talk to them about AAD details like the tenant and subscription to use. In particular, they will probably want you to create the app in their tenant, rather than an external one.
