### ISSUE TITLE
myresource - unclear what that stands for

### ISSUE THREAD

**Issue by ralphke** [Azure/AzureAuth#35]
The samples provided like 
token <- get_azure_token(resource="**myresource**", tenant="mytenant", app="**app_id**", ...) 
are unclear to us. 
Can you provide a sample what the string myresource might look like when accessing a Data Lake Gen2 storage account?
And what stands the app_id for? 
What is needed if I want to logon just with my AAD credentials? Why do I need an app_ID at all?
Thank you so much for your help.

**Comment by hongooi73** [comment]
Hi, I answered these questions before at https://github.com/Azure/AzureStor/issues/79:

The resource is `https://storage.azure.com/`
The app id is the ID of the app registration that you have to create in order to authenticate with AAD.

You need the app ID because the authentication process uses OAuth tokens, like with any other app that interacts with AAD. You can think of this package as being the rough R equivalent to the MSAL libraries for Python, C# etc. You supply all the necessary inputs to authenticate, and it gives you the token.

More info at Microsoft Docs [here](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory) and [here](https://docs.microsoft.com/en-au/azure/active-directory/develop/v2-overview).

**Comment by hongooi73** [comment]
You may be wondering, why do you need to supply a low-level implementation detail like an app ID, for a simple task like logging on to storage. That's because the storage team didn't think it necessary to create a first-party app registration for this purpose, which means everyone has to bring their own.

**Comment by hongooi73** [comment]
See also the vignette which was added to AzureStor in the last update: https://cran.r-project.org/web/packages/AzureStor/vignettes/aad.html

**Comment by ralphke** [comment]
Thank you so much, but I think I found the miss understanding here. You are referring to this AAD Authentifikation [article ](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory) for applications. But in we are looking for a [user based ](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad#overview-of-azure-ad-for-blobs-and-queues) or managed identity Authorization onto the Azure Data Lake Gen2 (hierarchy enabled) storage account [here](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction).
