### ISSUE TITLE
Azure Active Directory end of life?

### ISSUE THREAD

**Issue by courtwarr** [Azure/AzureAuth#49]
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

It looks like Microsoft is no longer developing AAD and recommending that all applications migrate to MSAL. Are there any plans to build a new R package for MSAL?

**Comment by hongooi73** [comment]
You misunderstand.

**Azure Active Directory (AAD)**, the service, is a technology for managing organisations and resources in Azure. This isn't going anywhere.

**Azure Active Directory Authentication Libraries (ADAL)** is a set of software packages for working with AAD. Versions of ADAL are available in C#, Javascript and Python. This is what's being deprecated.

**Microsoft Authentication Libraries (MSAL)** is the replacement for ADAL, and is similarly a set of C#, Javascript and Python packages for working with AAD.

AzureAuth is a substitute for ADAL and MSAL, since these libraries aren't available in R. Like AAD, AzureAuth isn't going anywhere.

**Comment by courtwarr** [comment]
Excellent. Thank you for the clarification!
