### ISSUE TITLE
Redirect to different urls depending on username

### ISSUE THREAD

**Issue by courtwarr** [Azure/AzureAuth#50]
More a question than an issue. I've got an internal corporate app and I'd like to restrict access to it. How might I go about redirecting unauthorized users to a different page? For a reprex, I'm running the example app nearly verbatim (vignettes/shiny.Rmd).

something like:

username <- decode_jwt(token)$payload$username

if(username %in% authorized) {
        redirect <- https://myapp.com
} else {
        redirect <- https://warningpage.com
}

**Comment by hongooi73** [comment]
I think this is beyond the scope of AzureAuth. If there are users you don't want to be able to access your app, then you should set their roles/permissions in AAD so that they can't authenticate in the first place. If that's not possible, then write your Shiny app so that it only displays the interface to the proper users: anyone else gets a dummy page.
