### ISSUE TITLE
Shinyapps.io with AAD

### ISSUE THREAD

**Issue by mjbroerman** [Azure/AzureAuth#51]
Hi, just following up on a comment [here](https://community.rstudio.com/t/is-it-possible-to-create-login-with-azure-active-directory-ad-in-shinyapps-io/42248/6), where the maintainer responded that it would be possible.

I have an app I want to deploy to shinyapps.io and implement my own authentication. It'd be nice to use our org's AAD. Incidentally, it will retrieve data as in this [issue](https://github.com/Azure/AzureAuth/issues/45), but all users will have the same experience, so I don't think it matters in this use case.

The [reply](https://github.com/Azure/AzureAuth/issues/27#issuecomment-611473170) to another issue suggests that this is the wrong solution for an externally hosted app.

Anyways, I am trying to retrieve the token. What is the "resource" in my case? I keep getting this error when authentication page is launched and I sign in:

```
The resource principal named {resource} was not found in the tenant named {tenant_id}.
```

**Comment by hongooi73** [comment]
Hi, it sounds like you're trying to use AAD for *authentication*, rather than *authorization*. The [previous issue](https://github.com/Azure/AzureAuth/issues/27) was unclear, but I took it to mean they had resources in AWS that they wanted to grant access to.

To do authentication, you want an ID token, as opposed to an access token. See the section ["OpenID connect"](https://github.com/Azure/AzureAuth#openid-connect) in the README for this repo.

**Comment by hongooi73** [comment]
Closing; ping me if you're still having problems.

**Comment by mjbroerman** [comment]
Yes sorry, was on vacation!
