### ISSUE TITLE
Prevent UI loading directly from ui_func

### ISSUE THREAD

**Issue by jadelhoss** [Azure/AzureAuth#57]
Hi Hong,

Thank you for your work with this and the M365R packages.

I have a shiny app, and use your boilerplate code for Shiny Authentication successfully. Users login using corporate credentials, and then access O365 data based on permissions.

What I notice though is that that UI will load even if a user is not from my company org. The app will disconnect only once a call is made to fetch SharePoint data, resulting in denied entry and app disconnection (so ok from data security). But can we prevent the UI from loading in the first place?

Is there a way to pull the email address (for example) directly from the ui_func() so that the UI will only load if user is from the same org, or email has certain characteristics (such as ending with @microsoft.com).

I have tried calling email from the server side, but this is too late in the process, and the UI is already loaded by then.

Thank in advance for the help,
Jad

**Comment by hongooi73** [comment]
You can examine the contents of the token with `decode_jwt`, before doing anything with it. Somewhere in there should be the email address of user. You can also paste the raw token text into a site like jwt.ms which will explain what the contents are.

Note this only works for a user who's logged in with an organisational (work & school account). If they authenticate with a personal account, the token will be in a custom format that isn't a regular JWT. Calling `decode_jwt` in this case will throw an error, so that can also be used to indicate they are not allowed.
