### ISSUE TITLE
Possible to connect to ADLS using only AAD username/credentials?

### ISSUE THREAD

**Issue by jennal-datacenter** [Azure/AzureAuth#66]
I'm trying to connect to our org's ADLS from RStudio using only my AAD username and password. For a while, we had a special app registered in Azure that was set to allow me access to certain blobs/data, which worked well with "get_azure_token()". 

However, for security reasons, our data warehouse manager wanted to get away from this app-driven method to one where everyone on our team only connects to ADLS from RStudio via our personal AAD usernames and passwords. It appears that this is only possible with "get_azure_token()" for "resource owners", which most members of our team are not.  

We have a setup right now where I'm signing into Azure from RStudio using the Azure CLI from the terminal, then using reticulate to run python scripts using the following:
from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient
import os, uuid
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient, __version__

I'm not totally literate at the Azure jargon or this python code, but as far as I have been told, there are no app id's or secrets or anything like that involved in this python workflow -- only the resource URL and the AAD username/password. Is a setup like this possible in R? What's going on in the python packages that makes this method of connection possible that doesn't seem possible the way I've been using AzureAuth, if you happen to know/if that's a reasonable way to ask this question? I guess another way to ask would be what exactly is an app, and why does app_id seem to be required for AzureAuth to work, while it isn't required for python?

Thanks for any help!

**Comment by hongooi73** [comment]
AzureAuth implements the standard procedures for logging in to Azure, as documented [here](https://docs.microsoft.com/en-au/azure/active-directory/develop/v2-overview). Supplying an application ID is part of this (note that if you use the "resource owner" authentication flow, you'd still have to supply the ID).

The Python package would be doing the same thing, but it's probably getting the app ID from a default source, eg an environment variable. You can ask your site admin for more details on this.  And provide the full syntax of your Python authentication call, otherwise I can't know what it's doing.

**Comment by hongooi73** [comment]
Closing; if you still have problems, email me or ask on Stack Overflow/RStudio community forums rather than opening another issue.
